### ISSUE TITLE
菜单栏渲染时，父节点标题长度太长导致显示不全问题

### ISSUE THREAD

**Issue by vvvviolet** [stepui/stepin-template#5]

**Comment by iczer** [comment]
可以适当调整侧边菜单宽度：
/src/theme/style/layout.less 文件增加以下代码
``` less
html {
     --width-side: 160px;
     --width-side-collapsed: 64px;
}
```
